232 Matched the naming convention for property url across project
notion-dotnet/notion-sdk-net pull request #238
Opened 2022-06-25 18:35 UTC by vijayvarmaD

## Description

Fixed the spelling and made the capitalization consistent across the project for the word "url".

It is being used in these formats:
1. "url" - JSON Property naming & variable naming
2.  "Url" - C# property & class naming
3.  "URL" - Constant field naming & Code Comments

Fixes # (issue)
#232

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Ran the unit tests as it was just the change in class & property names.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-06-26 20:06 UTC, KoditkarVedant commented
@vijayvarmaD I appreciate your contribution. One thing thought - would you mind creating separate PR for bugs are they are not related.

2022-06-26 20:07 UTC, KoditkarVedant requested changes
@vijayvarmaD  I appreciate your contribution. One thing though - would you mind creating separate PR for each issue as they are not related?

2022-06-27 02:18 UTC, vijayvarmaD commented
Sure.

2022-06-27 02:47 UTC, vijayvarmaD commented
@KoditkarVedant  Separated the commits. Can you plz review the PR. Thanks

2022-07-03 13:33 UTC, KoditkarVedant approved these changes

2022-07-03 13:45 UTC, merged